### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Smartuil** [Swilder-M/playstation-box#1]

**Comment by Smartuil** [comment]
![image](https://github.com/Swilder-M/playstation-box/assets/25101328/28f8af62-101d-4eac-89c4-f5c00aabf4ad)

**Comment by sigming** [comment]
hi, I'm not sure if Sony updated the api method or not, anyway the workaround for now is to follow the docs to re-fetch `PSN_NPSSO` and update it in the repository's settings and remove the secrets `PSN_ACCESS_TOKEN` and `PSN_REFRESH_TOKEN`, I tested it and it works fine: <https://github.com/Swilder-M/playstation-box/actions/runs/7623614063>

**Comment by Smartuil** [comment]
> hi, I'm not sure if Sony updated the api method or not, anyway the workaround for now is to follow the docs to re-fetch `PSN_NPSSO` and update it in the repository's settings and remove the secrets `PSN_ACCESS_TOKEN` and `PSN_REFRESH_TOKEN`, I tested it and it works fine: https://github.com/Swilder-M/playstation-box/actions/runs/7623614063

太感谢了老哥
